# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jarvis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cjarvis.proto\x12\x06server\"\x9b\x01\n\x0e\x45xecuteRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12\x0c\n\x04goal\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\x05\x12\x0c\n\x04task\x18\x04 \x01(\t\x12\x17\n\x0f\x64\x65pendent_tasks\x18\x05 \x03(\x05\x12\x10\n\x08skip_gen\x18\x06 \x01(\x08\x12\x1c\n\x14\x65nable_skill_library\x18\x07 \x01(\x08\"\x9d\x01\n\x0f\x45xecuteResponse\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12\x0c\n\x04goal\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\x05\x12\x0c\n\x04task\x18\x04 \x01(\t\x12\x0e\n\x06result\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12)\n\x08subtasks\x18\x07 \x03(\x0b\x32\x17.server.ExecuteResponse\";\n\x10SaveSkillRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12\x12\n\nskill_name\x18\x02 \x01(\t\"G\n\x11SaveSkillResponse\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xc6\x01\n\x06Jarvis\x12:\n\x07\x45xecute\x12\x16.server.ExecuteRequest\x1a\x17.server.ExecuteResponse\x12>\n\x0b\x45xecutePlan\x12\x16.server.ExecuteRequest\x1a\x17.server.ExecuteResponse\x12@\n\tSaveSkill\x12\x18.server.SaveSkillRequest\x1a\x19.server.SaveSkillResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jarvis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EXECUTEREQUEST']._serialized_start=25
  _globals['_EXECUTEREQUEST']._serialized_end=180
  _globals['_EXECUTERESPONSE']._serialized_start=183
  _globals['_EXECUTERESPONSE']._serialized_end=340
  _globals['_SAVESKILLREQUEST']._serialized_start=342
  _globals['_SAVESKILLREQUEST']._serialized_end=401
  _globals['_SAVESKILLRESPONSE']._serialized_start=403
  _globals['_SAVESKILLRESPONSE']._serialized_end=474
  _globals['_JARVIS']._serialized_start=477
  _globals['_JARVIS']._serialized_end=675
# @@protoc_insertion_point(module_scope)
